In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('predicted_outcomes.csv')
data

,gene_name,wt_res,mut_res,position,chain,dG,SecStruc,dS,subScore,grantham,...,buried_hydrophilic_introduced,buried_charge_introduced,buried_charge_switch,sec_struct_change,buried_charge_replaced,buried_exposed_switch,exposed_hydrophilic_introduced,Buried_salt_bridge_breakage,Large_helical_penality_in_alpha_helix,swaat_prediction
0,CYP2C9,E,G,272,A,-0.602,None,0.306,-2,98,...,0,0,0,0,0,0,0,0,0,1
1,CYP2C9,P,S,489,A,1.868,None,0.191,-1,74,...,0,0,0,0,0,0,0,0,0,1
2,CYP2C9,R,C,144,A,2.209,None,-0.193,-3,180,...,0,0,0,0,1,1,0,0,0,1
3,CYP2C9,N,S,457,A,-0.939,None,-0.533,1,46,...,0,0,0,0,0,0,0,0,0,0
4,CYP2C9,I,L,359,A,0.630,None,0.090,2,5,...,0,0,0,0,0,0,0,0,0,1
5,CYP2C9,R,L,125,A,-0.598,None,-0.069,-2,102,...,0,0,0,0,0,0,1,0,0,0
6,CYP2C9,D,A,397,A,0.023,None,0.089,-2,126,...,0,0,0,0,0,0,1,0,0,1

In [3]:
data['gene_name'].value_counts()

CYP2C9    7
Name: gene_name, dtype: int64

In [4]:
pos_col = data.loc[:, (data != 0).any(axis=0)]
pos_col

,gene_name,wt_res,mut_res,position,chain,dG,SecStruc,dS,subScore,grantham,...,hyrophob_WT,hyrophob_Mut,volume_WT,volume_Mut,pssm_mut,pssm_wt,buried_charge_replaced,buried_exposed_switch,exposed_hydrophilic_introduced,swaat_prediction
0,CYP2C9,E,G,272,A,-0.602,None,0.306,-2,98,...,0.67,0.10,84.7,36.3,-3,5,0,0,0,1
1,CYP2C9,P,S,489,A,1.868,None,0.191,-1,74,...,2.77,0.07,73.6,54.9,-4,9,0,0,0,1
2,CYP2C9,R,C,144,A,2.209,None,-0.193,-3,180,...,0.85,1.52,109.1,68.3,-2,8,1,1,0,1
3,CYP2C9,N,S,457,A,-0.939,None,-0.533,1,46,...,0.09,0.07,75.7,54.9,3,3,0,0,0,0
4,CYP2C9,I,L,359,A,0.630,None,0.090,2,5,...,3.15,2.17,102.0,102.0,1,5,0,0,0,1
5,CYP2C9,R,L,125,A,-0.598,None,-0.069,-2,102,...,0.85,2.17,109.1,102.0,-6,8,0,0,1,0
6,CYP2C9,D,A,397,A,0.023,None,0.089,-2,126,...,0.66,0.87,68.4,52.6,-5,8,0,0,1,1

In [5]:
pos_swaat_pred = pos_col.loc[(data['swaat_prediction'] == 1)]
pos_swaat_pred

,gene_name,wt_res,mut_res,position,chain,dG,SecStruc,dS,subScore,grantham,...,hyrophob_WT,hyrophob_Mut,volume_WT,volume_Mut,pssm_mut,pssm_wt,buried_charge_replaced,buried_exposed_switch,exposed_hydrophilic_introduced,swaat_prediction
0,CYP2C9,E,G,272,A,-0.602,None,0.306,-2,98,...,0.67,0.10,84.7,36.3,-3,5,0,0,0,1
1,CYP2C9,P,S,489,A,1.868,None,0.191,-1,74,...,2.77,0.07,73.6,54.9,-4,9,0,0,0,1
2,CYP2C9,R,C,144,A,2.209,None,-0.193,-3,180,...,0.85,1.52,109.1,68.3,-2,8,1,1,0,1
4,CYP2C9,I,L,359,A,0.630,None,0.090,2,5,...,3.15,2.17,102.0,102.0,1,5,0,0,0,1
6,CYP2C9,D,A,397,A,0.023,None,0.089,-2,126,...,0.66,0.87,68.4,52.6,-5,8,0,0,1,1

In [6]:
bad_dG = pos_col[(pos_col['dG'] > 0.500) | (pos_col['dG'] < -0.500)]
bad_dG

,gene_name,wt_res,mut_res,position,chain,dG,SecStruc,dS,subScore,grantham,...,hyrophob_WT,hyrophob_Mut,volume_WT,volume_Mut,pssm_mut,pssm_wt,buried_charge_replaced,buried_exposed_switch,exposed_hydrophilic_introduced,swaat_prediction
0,CYP2C9,E,G,272,A,-0.602,None,0.306,-2,98,...,0.67,0.10,84.7,36.3,-3,5,0,0,0,1
1,CYP2C9,P,S,489,A,1.868,None,0.191,-1,74,...,2.77,0.07,73.6,54.9,-4,9,0,0,0,1
2,CYP2C9,R,C,144,A,2.209,None,-0.193,-3,180,...,0.85,1.52,109.1,68.3,-2,8,1,1,0,1
3,CYP2C9,N,S,457,A,-0.939,None,-0.533,1,46,...,0.09,0.07,75.7,54.9,3,3,0,0,0,0
4,CYP2C9,I,L,359,A,0.630,None,0.090,2,5,...,3.15,2.17,102.0,102.0,1,5,0,0,0,1
5,CYP2C9,R,L,125,A,-0.598,None,-0.069,-2,102,...,0.85,2.17,109.1,102.0,-6,8,0,0,1,0

In [7]:
bad_dS = pos_col[(pos_col['dS'] > 0.500) | (pos_col['dS'] < -0.500)]
bad_dS

,gene_name,wt_res,mut_res,position,chain,dG,SecStruc,dS,subScore,grantham,...,hyrophob_WT,hyrophob_Mut,volume_WT,volume_Mut,pssm_mut,pssm_wt,buried_charge_replaced,buried_exposed_switch,exposed_hydrophilic_introduced,swaat_prediction
3,CYP2C9,N,S,457,A,-0.939,None,-0.533,1,46,...,0.09,0.07,75.7,54.9,3,3,0,0,0,0

In [8]:
combined = [bad_dG, bad_dS]
combined = pd.concat(combined)
bad_dG_dS = combined[combined.duplicated()]
bad_dG_dS

,gene_name,wt_res,mut_res,position,chain,dG,SecStruc,dS,subScore,grantham,...,hyrophob_WT,hyrophob_Mut,volume_WT,volume_Mut,pssm_mut,pssm_wt,buried_charge_replaced,buried_exposed_switch,exposed_hydrophilic_introduced,swaat_prediction
3,CYP2C9,N,S,457,A,-0.939,None,-0.533,1,46,...,0.09,0.07,75.7,54.9,3,3,0,0,0,0

In [ ]:
# d_rf.to_csv('positive_columns.csv', index=False)

In [ ]:
# sp_deleterious.to_csv('positive_swaat_prediction.csv', index=False)

In [ ]:
# bad_dG_dS.to_csv('deleterios_dG_and_dS.csv', index=False)